[package]
name = "nes-bundler"
version = "0.1.0"
authors = ["Ted Steen <ted.steen@gmail.com>"]
edition = "2021"
publish = false
resolver="2"

[features]
default = ["netplay"]
netplay = ["matchbox_socket", "tokio", "ggrs", "futures-timer", "futures"]

[dependencies]
anyhow = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
gilrs = { version = "0.9", features = ["serde-serialize"] }
winit = {version = "0.26", features = ["serde"] }
pixels = "0.9"
egui = "0.18"
egui-wgpu = "0.18"
egui-winit = "0.18"
game-loop = { version = "0.9", features = ["window"] }
cpal = "0.13"
ringbuf = "0.2"
rusticnes-core = { git = "https://github.com/tedsteen/rusticnes-core", branch = "for-rusticnes-test" }

# Netplay deps
matchbox_socket = { git = "https://github.com/johanhelsing/matchbox", features = ["ggrs-socket"], optional = true }
futures-timer = { version = "3", features = ["wasm-bindgen"], optional = true }
ggrs = { version = "0.9", optional = true }
tokio = { version = "1", features = ["rt"], optional = true }
futures = {version = "0.3", optional = true }