[package]
name = "rusticnes-test"
version = "0.1.0"
authors = ["Ted Steen <ted.steen@gmail.com>"]
edition = "2021"
publish = false
resolver="2"

[features]
default = ["netplay"]
netplay = ["matchbox_socket", "ggrs", "futures-timer", "futures"]

[dependencies]
env_logger = "0.9"
log = "0.4"
anyhow = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
gilrs = { version = "0.9", features = ["serde-serialize"] }

winit = {version = "0.26", features = ["serde"] }
pixels = "0.9"
# rfd = "0.4" # Open file dialog for loading new ROMs?
egui = "0.18"
egui-wgpu = "0.18"
egui-winit = "0.18"
game-loop = { version = "0.9", features = ["window"] }
cpal = "0.13"
ringbuf = "0.2"

bincode = "1.3"
# rusticnes-core = { git = "https://github.com/zeta0134/rusticnes-core" }
# rusticnes-core = { path = "../rusticnes-core" }
rusticnes-core = { git = "https://github.com/tedsteen/rusticnes-core", branch = "for-rusticnes-test" }

matchbox_socket = { git = "https://github.com/johanhelsing/matchbox", features = ["ggrs-socket"], optional = true }
futures-timer = { version = "3", features = ["wasm-bindgen"], optional = true }
ggrs = { version = "0.9", optional = true }

tokio = { version = "1.12", features = ["full"] }
futures = {version = "0.3", optional = true }
structopt = "0.3"