[package]
name = "rusticnes-test"
version = "0.1.0"
authors = ["Ted Steen <ted.steen@gmail.com>"]
edition = "2021"
publish = false
resolver="2"

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize", "netplay"]
netplay = ["ggrs", "webrtc", "webrtc_data", "libp2p", "futures", "serde"]

[dependencies]
env_logger = "0.9"
log = "0.4"

winit = "0.26"

pixels = "0.9"

# rfd = "0.4" # Open file dialog for loading new ROMs?
egui = "0.18"
egui-wgpu = "0.18"
egui-winit = "0.18"

cpal = "0.13"
ringbuf = "0.2"

game-loop = { version = "0.9", features = ["window"] }

ggrs = { version = "0.9", optional = true }
bincode = "1.3"

webrtc = { version = "0.4", optional = true }
webrtc_data = { package = "webrtc-data", version = "0.3", optional = true }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
libp2p = {version = "0.45", features = ["kad"], optional = true}
futures = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

structopt = "0.3"

# rusticnes-core = { git = "https://github.com/zeta0134/rusticnes-core" }
rusticnes-core = { path = "../rusticnes-core" }
# rusticnes-core = { git = "https://github.com/tedsteen/rusticnes-core", branch = "for-rusticnes-test" }
